-- 博客文章管理后台数据库升级
-- 在 Supabase SQL Editor 中执行一次。

alter table public.profiles
  add column if not exists is_admin boolean not null default false;

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 300),
  type text not null check (char_length(type) between 1 and 30),
  tags text[] not null default '{}',
  read_time text not null default '5 分钟',
  lead text not null check (char_length(lead) between 1 and 500),
  body text not null,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 旧版本只保存发布日期。升级后保留原日期，并按北京时间 00:00:00 转换；
-- 新发布的文章会完整保存到秒和时区。
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'posts'
      and column_name = 'published_at'
      and data_type = 'date'
  ) then
    alter table public.posts alter column published_at drop default;
    alter table public.posts alter column published_at type timestamptz
      using (published_at::timestamp at time zone 'Asia/Shanghai');
  end if;
end;
$$;

alter table public.posts alter column published_at set default now();

create index if not exists posts_status_published_at_idx
  on public.posts(status, published_at desc);

alter table public.posts enable row level security;

-- 普通用户只能修改昵称和头像，不能把自己提升为管理员。
revoke update on table public.profiles from authenticated;
grant update (username, avatar_url) on table public.profiles to authenticated;

drop policy if exists "Published posts are publicly readable" on public.posts;
drop policy if exists "Admins read all posts" on public.posts;
drop policy if exists "Admins create posts" on public.posts;
drop policy if exists "Admins update posts" on public.posts;
drop policy if exists "Admins delete posts" on public.posts;

create policy "Published posts are publicly readable"
  on public.posts for select
  using (status = 'published');

create policy "Admins read all posts"
  on public.posts for select
  using (exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  ));

create policy "Admins create posts"
  on public.posts for insert
  with check (
    author_id = auth.uid() and exists (
      select 1 from public.profiles
      where id = auth.uid() and is_admin = true
    )
  );

create policy "Admins update posts"
  on public.posts for update
  using (exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  ));

create policy "Admins delete posts"
  on public.posts for delete
  using (exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin = true
  ));

-- 把下面的邮箱替换成你的博客注册邮箱，然后保留并执行。
update public.profiles
set is_admin = true
where id = (
  select id from auth.users
  where email = 'YOUR_BLOG_EMAIL'
);
