-- cnbdg 单社区体验升级
-- 参考贴吧的帖子信息流、精品/置顶、收藏、楼层浏览与回复通知；不创建分区或“吧”。
-- 前置：community.sql、forum-interactions.sql、social-inbox.sql、governance.sql。
-- 可重复执行，不会删除帖子、回复、用户、点赞或既有通知。

alter table public.forum_posts
  add column if not exists topic_type text not null default 'discussion',
  add column if not exists is_pinned boolean not null default false,
  add column if not exists is_featured boolean not null default false,
  add column if not exists view_count bigint not null default 0;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'forum_posts_topic_type_check'
      and conrelid = 'public.forum_posts'::regclass
  ) then
    alter table public.forum_posts add constraint forum_posts_topic_type_check
      check (topic_type in ('discussion', 'question', 'share', 'guide'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'forum_posts_view_count_check'
      and conrelid = 'public.forum_posts'::regclass
  ) then
    alter table public.forum_posts add constraint forum_posts_view_count_check
      check (view_count >= 0);
  end if;
end
$$;

create index if not exists forum_posts_pinned_updated_idx
  on public.forum_posts(is_pinned desc, updated_at desc);
create index if not exists forum_posts_featured_updated_idx
  on public.forum_posts(is_featured, updated_at desc)
  where is_featured = true;
create index if not exists forum_posts_topic_type_updated_idx
  on public.forum_posts(topic_type, updated_at desc);

-- 普通用户只能新增/修改帖子正文、标题和类型，不能直接给自己置顶、加精或刷浏览量。
revoke insert on table public.forum_posts from authenticated;
revoke update on table public.forum_posts from authenticated;
grant insert (author_id, title, content, topic_type, updated_at) on table public.forum_posts to authenticated;
grant update (title, content, topic_type, updated_at) on table public.forum_posts to authenticated;

create or replace function public.normalize_forum_post_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := now();
    new.updated_at := now();
    new.is_pinned := false;
    new.is_featured := false;
    new.view_count := 0;
    new.likes := 0;
  -- community.sql 的回复触发器会嵌套更新帖子时间；仅允许这类数据库内部更新通过。
  elsif pg_trigger_depth() > 1 and new.updated_at is distinct from old.updated_at then
    new.updated_at := new.updated_at;
  elsif new.title is distinct from old.title
     or new.content is distinct from old.content
     or new.topic_type is distinct from old.topic_type then
    new.updated_at := now();
  else
    new.updated_at := old.updated_at;
  end if;
  return new;
end;
$$;

drop trigger if exists normalize_forum_post_write_trigger on public.forum_posts;
create trigger normalize_forum_post_write_trigger
  before insert or update on public.forum_posts
  for each row execute function public.normalize_forum_post_write();

create table if not exists public.forum_bookmarks (
  user_id uuid not null references public.profiles(id) on delete cascade,
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, post_id)
);

create index if not exists forum_bookmarks_user_created_idx
  on public.forum_bookmarks(user_id, created_at desc);

create table if not exists public.forum_post_views (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.forum_posts(id) on delete cascade,
  viewer_id uuid references public.profiles(id) on delete cascade,
  viewer_key text,
  viewed_on date not null default current_date,
  created_at timestamptz not null default now(),
  check (
    (viewer_id is not null and viewer_key is null)
    or (viewer_id is null and viewer_key is not null and char_length(viewer_key) between 16 and 80)
  )
);

create unique index if not exists forum_post_views_user_day_idx
  on public.forum_post_views(post_id, viewer_id, viewed_on)
  where viewer_id is not null;
create unique index if not exists forum_post_views_guest_day_idx
  on public.forum_post_views(post_id, viewer_key, viewed_on)
  where viewer_id is null;

alter table public.forum_bookmarks enable row level security;
alter table public.forum_post_views enable row level security;
revoke all on table public.forum_bookmarks from anon, authenticated;
revoke all on table public.forum_post_views from anon, authenticated;

drop policy if exists "Users read own forum bookmarks" on public.forum_bookmarks;
create policy "Users read own forum bookmarks"
  on public.forum_bookmarks for select to authenticated
  using (auth.uid() = user_id);

create or replace function public.list_my_forum_bookmarks()
returns table (post_id bigint, created_at timestamptz)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  return query
  select b.post_id, b.created_at
  from public.forum_bookmarks b
  where b.user_id = auth.uid()
  order by b.created_at desc;
end;
$$;

create or replace function public.toggle_forum_bookmark(p_post_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  already_bookmarked boolean;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not exists(select 1 from public.forum_posts p where p.id = p_post_id) then raise exception 'TARGET_NOT_FOUND'; end if;
  select exists(
    select 1 from public.forum_bookmarks b
    where b.user_id = auth.uid() and b.post_id = p_post_id
  ) into already_bookmarked;
  if already_bookmarked then
    delete from public.forum_bookmarks b where b.user_id = auth.uid() and b.post_id = p_post_id;
    return false;
  end if;
  insert into public.forum_bookmarks(user_id, post_id) values (auth.uid(), p_post_id);
  return true;
end;
$$;

create or replace function public.record_forum_view(p_post_id bigint, p_viewer_key text default null)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer := 0;
  total bigint;
  clean_key text := trim(coalesce(p_viewer_key, ''));
begin
  if not exists(select 1 from public.forum_posts p where p.id = p_post_id) then raise exception 'TARGET_NOT_FOUND'; end if;
  if auth.uid() is not null then
    insert into public.forum_post_views(post_id, viewer_id)
    values (p_post_id, auth.uid()) on conflict do nothing;
    get diagnostics inserted_count = row_count;
  elsif clean_key ~ '^[A-Za-z0-9_-]{16,80}$' then
    insert into public.forum_post_views(post_id, viewer_key)
    values (p_post_id, clean_key) on conflict do nothing;
    get diagnostics inserted_count = row_count;
  end if;
  if inserted_count > 0 then
    update public.forum_posts p set view_count = p.view_count + 1 where p.id = p_post_id;
  end if;
  select p.view_count into total from public.forum_posts p where p.id = p_post_id;
  return coalesce(total, 0);
end;
$$;

create or replace function public.get_forum_thread_state(p_post_id bigint)
returns table (bookmarked boolean, post_liked boolean, liked_reply_ids bigint[])
language sql
stable
security definer
set search_path = public
as $$
  select
    auth.uid() is not null and exists(
      select 1 from public.forum_bookmarks b
      where b.user_id = auth.uid() and b.post_id = p_post_id
    ),
    auth.uid() is not null and exists(
      select 1 from public.forum_reactions r
      where r.user_id = auth.uid() and r.target_type = 'post' and r.target_id = p_post_id
    ),
    coalesce(array(
      select r.target_id from public.forum_reactions r
      join public.forum_replies reply on reply.id = r.target_id
      where r.user_id = auth.uid() and r.target_type = 'reply' and reply.post_id = p_post_id
    ), '{}'::bigint[]);
$$;

create or replace function public.admin_set_forum_post_status(
  p_post_id bigint,
  p_is_pinned boolean,
  p_is_featured boolean
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  post_author uuid;
  post_title text;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select p.author_id, p.title into post_author, post_title
  from public.forum_posts p where p.id = p_post_id for update;
  if not found then raise exception 'TARGET_NOT_FOUND'; end if;
  update public.forum_posts p
  set is_pinned = coalesce(p_is_pinned, false), is_featured = coalesce(p_is_featured, false)
  where p.id = p_post_id;
  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'manage_forum_post', post_author,
    jsonb_build_object('post_id', p_post_id, 'title', post_title,
      'is_pinned', coalesce(p_is_pinned, false), 'is_featured', coalesce(p_is_featured, false)));
  return true;
end;
$$;

-- 回复帖子或楼中楼时通知对应用户。
alter table public.notifications drop constraint if exists notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check
  check (kind in ('follow', 'forum_like', 'comment_like', 'direct_message', 'forum_reply', 'group_message'));

create or replace function public.notify_forum_reply_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recipient uuid;
  post_title text;
  notice_message text;
begin
  select p.title into post_title from public.forum_posts p where p.id = new.post_id;
  if new.parent_id is not null then
    select r.author_id into recipient from public.forum_replies r where r.id = new.parent_id;
    notice_message := '回复了你的楼层';
  else
    select p.author_id into recipient from public.forum_posts p where p.id = new.post_id;
    notice_message := '回复了你的帖子';
  end if;
  if recipient is not null and recipient <> new.author_id then
    insert into public.notifications(recipient_id, actor_id, kind, target_type, target_id, payload)
    values (recipient, new.author_id, 'forum_reply', 'forum_post', new.post_id,
      jsonb_build_object('message', notice_message, 'title', post_title,
        'floor', new.floor_number, 'reply_id', new.id));
  end if;
  return new;
end;
$$;

drop trigger if exists after_forum_reply_notification on public.forum_replies;
create trigger after_forum_reply_notification
  after insert on public.forum_replies
  for each row execute function public.notify_forum_reply_created();

revoke all on function public.list_my_forum_bookmarks() from public;
revoke all on function public.normalize_forum_post_write() from public;
revoke all on function public.toggle_forum_bookmark(bigint) from public;
revoke all on function public.record_forum_view(bigint, text) from public;
revoke all on function public.get_forum_thread_state(bigint) from public;
revoke all on function public.admin_set_forum_post_status(bigint, boolean, boolean) from public;
revoke all on function public.notify_forum_reply_created() from public;

grant execute on function public.list_my_forum_bookmarks() to authenticated;
grant execute on function public.toggle_forum_bookmark(bigint) to authenticated;
grant execute on function public.record_forum_view(bigint, text) to anon, authenticated;
grant execute on function public.get_forum_thread_state(bigint) to anon, authenticated;
grant execute on function public.admin_set_forum_post_status(bigint, boolean, boolean) to authenticated;

notify pgrst, 'reload schema';
