-- 社区楼中楼与点赞升级
-- 先执行 community.sql，再执行本脚本一次。
-- 不会删除现有帖子或回复。

alter table public.forum_posts
  add column if not exists likes integer not null default 0;

alter table public.forum_replies
  add column if not exists parent_id bigint references public.forum_replies(id) on delete cascade,
  add column if not exists likes integer not null default 0;

alter table public.forum_posts
  drop constraint if exists forum_posts_likes_check;
alter table public.forum_posts
  add constraint forum_posts_likes_check check (likes >= 0);

alter table public.forum_replies
  drop constraint if exists forum_replies_likes_check;
alter table public.forum_replies
  add constraint forum_replies_likes_check check (likes >= 0);

create index if not exists forum_replies_parent_id_idx
  on public.forum_replies(parent_id);

create table if not exists public.forum_reactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('post', 'reply')),
  target_id bigint not null,
  created_at timestamptz not null default now(),
  unique (user_id, target_type, target_id)
);

alter table public.forum_reactions enable row level security;
revoke all on table public.forum_reactions from anon, authenticated;

create or replace function public.check_forum_reply_parent()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.parent_id is not null and not exists (
    select 1 from public.forum_replies
    where id = new.parent_id and post_id = new.post_id
  ) then
    raise exception 'INVALID_REPLY_PARENT';
  end if;
  return new;
end;
$$;

drop trigger if exists before_forum_reply_parent_check on public.forum_replies;
create trigger before_forum_reply_parent_check
  before insert on public.forum_replies
  for each row execute procedure public.check_forum_reply_parent();

create or replace function public.toggle_forum_like(p_target_type text, p_target_id bigint)
returns table (liked boolean, likes integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  already_liked boolean;
  total integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_target_type not in ('post', 'reply') then raise exception 'INVALID_LIKE_TARGET'; end if;
  if p_target_type = 'post' and not exists (select 1 from public.forum_posts where id = p_target_id) then
    raise exception 'TARGET_NOT_FOUND';
  elsif p_target_type = 'reply' and not exists (select 1 from public.forum_replies where id = p_target_id) then
    raise exception 'TARGET_NOT_FOUND';
  end if;

  select exists (
    select 1 from public.forum_reactions
    where user_id = auth.uid() and forum_reactions.target_type = p_target_type
      and forum_reactions.target_id = p_target_id
  ) into already_liked;

  if already_liked then
    delete from public.forum_reactions
    where user_id = auth.uid() and forum_reactions.target_type = p_target_type
      and forum_reactions.target_id = p_target_id;
  else
    insert into public.forum_reactions(user_id, target_type, target_id)
    values (auth.uid(), p_target_type, p_target_id);
  end if;

  if p_target_type = 'post' then
    select count(*)::integer into total from public.forum_reactions where forum_reactions.target_type = 'post' and forum_reactions.target_id = p_target_id;
    update public.forum_posts set likes = total where id = p_target_id;
  else
    select count(*)::integer into total from public.forum_reactions where forum_reactions.target_type = 'reply' and forum_reactions.target_id = p_target_id;
    update public.forum_replies set likes = total where id = p_target_id;
  end if;
  return query select not already_liked, total;
end;
$$;

revoke all on function public.toggle_forum_like(text, bigint) from public;
grant execute on function public.toggle_forum_like(text, bigint) to authenticated;

-- 确保旧的论坛读取/新增权限继续存在，点赞计数由 RPC 统一维护。
grant select on table public.forum_posts, public.forum_replies to anon, authenticated;
grant insert, update, delete on table public.forum_posts, public.forum_replies to authenticated;
grant usage, select on all sequences in schema public to authenticated;
