-- cnbdg 社区治理中心 V2
-- 前置：已执行 community.sql、user-identity.sql、moderation.sql、admin-panel.sql。
-- 本脚本可重复执行；不会删除用户、内容、举报、处罚或操作日志。

alter table public.profiles
  add column if not exists title_locked boolean not null default false;

-- 再次收紧资料表列权限：普通用户永远不能直接修改 UID、角色或头衔锁定状态。
revoke update on table public.profiles from authenticated;
grant update (username, avatar_url, display_title) on table public.profiles to authenticated;

create or replace function public.protect_profile_governance_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() = old.id and not public.current_user_is_admin() then
    if new.is_admin is distinct from old.is_admin
       or new.user_uid is distinct from old.user_uid
       or new.title_locked is distinct from old.title_locked then
      raise exception 'PROTECTED_PROFILE_FIELD';
    end if;
    if old.title_locked and new.display_title is distinct from old.display_title then
      raise exception 'TITLE_LOCKED';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_governance_fields_trigger on public.profiles;
create trigger protect_profile_governance_fields_trigger
  before update on public.profiles
  for each row execute function public.protect_profile_governance_fields();

-- 保留此前指定给 UID 2 的专属称号，并纳入站长头衔锁定机制。
update public.profiles
set display_title = '罗布乐思小鸡鸡', title_locked = true
where user_uid = 2;

alter table public.user_moderation
  add column if not exists active boolean not null default true,
  add column if not exists category text not null default 'other',
  add column if not exists scope text not null default 'community';

alter table public.content_reports
  add column if not exists category text not null default 'other',
  add column if not exists priority text not null default 'normal',
  add column if not exists decision text,
  add column if not exists review_note text;

-- 升级前已经到期的限制标记为失效；永久限制（banned_until 为空）保持生效。
update public.user_moderation
set active = false
where active = true and banned_until is not null and banned_until <= now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'user_moderation_category_check'
      and conrelid = 'public.user_moderation'::regclass
  ) then
    alter table public.user_moderation add constraint user_moderation_category_check
      check (category in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'user_moderation_scope_check'
      and conrelid = 'public.user_moderation'::regclass
  ) then
    alter table public.user_moderation add constraint user_moderation_scope_check
      check (scope in ('community', 'all_social'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'content_reports_category_check'
      and conrelid = 'public.content_reports'::regclass
  ) then
    alter table public.content_reports add constraint content_reports_category_check
      check (category in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'content_reports_priority_check'
      and conrelid = 'public.content_reports'::regclass
  ) then
    alter table public.content_reports add constraint content_reports_priority_check
      check (priority in ('normal', 'high', 'urgent'));
  end if;
end
$$;

create table if not exists public.moderation_strikes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  report_id bigint references public.content_reports(id) on delete set null,
  category text not null check (category in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other')),
  points smallint not null default 1 check (points between 1 and 10),
  reason text not null check (char_length(reason) between 2 and 500),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists moderation_strikes_user_created_idx
  on public.moderation_strikes(user_id, created_at desc);

create table if not exists public.moderation_appeals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  action_id bigint references public.moderation_actions(id) on delete set null,
  reason text not null check (char_length(reason) between 10 and 500),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  review_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists moderation_appeals_one_pending_idx
  on public.moderation_appeals(user_id)
  where status = 'pending';

create index if not exists moderation_appeals_status_created_idx
  on public.moderation_appeals(status, created_at desc);

alter table public.moderation_strikes enable row level security;
alter table public.moderation_appeals enable row level security;

revoke all on table public.moderation_strikes from anon, authenticated;
revoke all on table public.moderation_appeals from anon, authenticated;
grant select on table public.moderation_strikes to authenticated;
grant select on table public.moderation_appeals to authenticated;

drop policy if exists "Admins read moderation strikes" on public.moderation_strikes;
create policy "Admins read moderation strikes"
  on public.moderation_strikes for select
  using (public.current_user_is_admin());

drop policy if exists "Users read own appeals or admins read all" on public.moderation_appeals;
create policy "Users read own appeals or admins read all"
  on public.moderation_appeals for select
  using (auth.uid() = user_id or public.current_user_is_admin());

create or replace function public.current_user_can_participate()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null and not exists (
    select 1 from public.user_moderation m
    where m.user_id = auth.uid()
      and m.active = true
      and (m.banned_until is null or m.banned_until > now())
  );
$$;

create or replace function public.get_my_moderation()
returns table (banned boolean, banned_until timestamptz, reason text)
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false) as banned,
    m.banned_until,
    m.reason
  from (select auth.uid() as id) me
  left join public.user_moderation m on m.user_id = me.id;
$$;

create or replace function public.get_my_governance_status()
returns table (
  restricted boolean,
  restricted_until timestamptz,
  restriction_reason text,
  restriction_category text,
  strike_count bigint,
  pending_appeal boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  return query
  select
    coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false),
    m.banned_until,
    m.reason,
    m.category,
    (select count(*) from public.moderation_strikes s where s.user_id = auth.uid()),
    exists(select 1 from public.moderation_appeals a where a.user_id = auth.uid() and a.status = 'pending')
  from (select auth.uid() as id) me
  left join public.user_moderation m on m.user_id = me.id;
end;
$$;

create or replace function public.report_content_v2(
  report_target_type text,
  report_target_id bigint,
  report_category text,
  report_reason text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
  target_exists boolean;
  report_priority text;
begin
  if not public.current_user_can_participate() then raise exception 'ACCOUNT_RESTRICTED'; end if;
  if report_target_type not in ('forum_post', 'forum_reply', 'blog_comment') then raise exception 'INVALID_TARGET'; end if;
  if report_category not in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other') then raise exception 'INVALID_CATEGORY'; end if;
  if char_length(trim(report_reason)) not between 2 and 300 then raise exception 'INVALID_REASON'; end if;

  if report_target_type = 'forum_post' then
    select exists(select 1 from public.forum_posts where id = report_target_id) into target_exists;
  elsif report_target_type = 'forum_reply' then
    select exists(select 1 from public.forum_replies where id = report_target_id) into target_exists;
  else
    select exists(select 1 from public.comments where id = report_target_id) into target_exists;
  end if;
  if not target_exists then raise exception 'TARGET_NOT_FOUND'; end if;

  report_priority := case when report_category in ('privacy', 'illegal') then 'high' else 'normal' end;
  insert into public.content_reports(reporter_id, target_type, target_id, category, priority, reason)
  values (auth.uid(), report_target_type, report_target_id, report_category, report_priority, trim(report_reason))
  returning id into new_id;
  return new_id;
exception
  when unique_violation then raise exception 'ALREADY_REPORTED';
end;
$$;

create or replace function public.admin_governance_overview()
returns table (
  pending_reports bigint,
  restricted_users bigint,
  pending_appeals bigint,
  actions_today bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query select
    (select count(*) from public.content_reports r where r.status = 'pending'),
    (select count(*) from public.user_moderation m where m.active = true and (m.banned_until is null or m.banned_until > now())),
    (select count(*) from public.moderation_appeals a where a.status = 'pending'),
    (select count(*) from public.moderation_actions ma where ma.created_at >= date_trunc('day', now()));
end;
$$;

create or replace function public.admin_get_member_by_uid(requested_uid bigint)
returns table (
  user_id uuid,
  user_uid bigint,
  username text,
  avatar_url text,
  display_title text,
  is_admin boolean,
  created_at timestamptz,
  restricted boolean,
  restricted_until timestamptz,
  restriction_reason text,
  strike_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select p.id, p.user_uid, p.username, p.avatar_url, p.display_title, p.is_admin, p.created_at,
    coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false),
    m.banned_until, m.reason,
    (select count(*) from public.moderation_strikes s where s.user_id = p.id)
  from public.profiles p
  left join public.user_moderation m on m.user_id = p.id
  where p.user_uid = requested_uid
  limit 1;
end;
$$;

create or replace function public.admin_list_moderation_users(
  status_filter text default 'all',
  search_text text default '',
  row_limit integer default 100
)
returns table (
  user_id uuid,
  user_uid bigint,
  username text,
  avatar_url text,
  display_title text,
  is_admin boolean,
  created_at timestamptz,
  restricted boolean,
  restricted_until timestamptz,
  restriction_reason text,
  restriction_category text,
  strike_count bigint,
  forum_post_count bigint,
  forum_reply_count bigint,
  report_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select p.id, p.user_uid, p.username, p.avatar_url, p.display_title, p.is_admin, p.created_at,
    coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false),
    m.banned_until, m.reason, m.category,
    (select count(*) from public.moderation_strikes s where s.user_id = p.id),
    (select count(*) from public.forum_posts fp where fp.author_id = p.id),
    (select count(*) from public.forum_replies fr where fr.author_id = p.id),
    (select count(*) from public.content_reports cr
      where cr.target_type = 'forum_post' and cr.target_id in (select fp2.id from public.forum_posts fp2 where fp2.author_id = p.id)
         or cr.target_type = 'forum_reply' and cr.target_id in (select fr2.id from public.forum_replies fr2 where fr2.author_id = p.id)
         or cr.target_type = 'blog_comment' and cr.target_id in (select c2.id from public.comments c2 where c2.author_id = p.id))
  from public.profiles p
  left join public.user_moderation m on m.user_id = p.id
  where (
    trim(coalesce(search_text, '')) = ''
    or p.username ilike '%' || trim(search_text) || '%'
    or p.user_uid::text = trim(search_text)
    or p.display_title ilike '%' || trim(search_text) || '%'
  )
  and (
    status_filter = 'all'
    or status_filter = 'admin' and p.is_admin = true
    or status_filter = 'restricted' and coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false)
    or status_filter = 'normal' and not p.is_admin and not coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false)
  )
  order by
    coalesce(m.active and (m.banned_until is null or m.banned_until > now()), false) desc,
    p.created_at desc
  limit greatest(1, least(coalesce(row_limit, 100), 300));
end;
$$;

create or replace function public.admin_list_moderation_reports(
  status_filter text default 'all',
  search_text text default '',
  row_limit integer default 100
)
returns table (
  report_id bigint,
  target_type text,
  target_id bigint,
  category text,
  priority text,
  reason text,
  status text,
  created_at timestamptz,
  reporter_name text,
  target_author_id uuid,
  target_author_uid bigint,
  target_author_name text,
  target_author_title text,
  content_excerpt text,
  decision text,
  review_note text,
  reviewed_at timestamptz,
  reviewer_name text
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  with report_rows as (
    select r.*,
      case r.target_type
        when 'forum_post' then (select fp.author_id from public.forum_posts fp where fp.id = r.target_id)
        when 'forum_reply' then (select fr.author_id from public.forum_replies fr where fr.id = r.target_id)
        else (select c.author_id from public.comments c where c.id = r.target_id)
      end as author_id,
      left(coalesce(case r.target_type
        when 'forum_post' then (select fp.title || E'\n' || fp.content from public.forum_posts fp where fp.id = r.target_id)
        when 'forum_reply' then (select fr.content from public.forum_replies fr where fr.id = r.target_id)
        else (select c.content from public.comments c where c.id = r.target_id)
      end, '[内容已删除]'), 500) as excerpt
    from public.content_reports r
  )
  select q.id, q.target_type, q.target_id, q.category, q.priority, q.reason, q.status, q.created_at,
    reporter.username, author.id, author.user_uid, author.username, author.display_title, q.excerpt,
    q.decision, q.review_note, q.reviewed_at, reviewer.username
  from report_rows q
  join public.profiles reporter on reporter.id = q.reporter_id
  left join public.profiles author on author.id = q.author_id
  left join public.profiles reviewer on reviewer.id = q.reviewed_by
  where (status_filter = 'all' or q.status = status_filter)
    and (
      trim(coalesce(search_text, '')) = ''
      or q.reason ilike '%' || trim(search_text) || '%'
      or q.excerpt ilike '%' || trim(search_text) || '%'
      or reporter.username ilike '%' || trim(search_text) || '%'
      or author.username ilike '%' || trim(search_text) || '%'
      or author.user_uid::text = trim(search_text)
    )
  order by (q.status = 'pending') desc, (q.priority = 'urgent') desc, (q.priority = 'high') desc, q.created_at desc
  limit greatest(1, least(coalesce(row_limit, 100), 300));
end;
$$;

create or replace function public.admin_list_moderation_actions(
  search_text text default '',
  row_limit integer default 100
)
returns table (
  action_id bigint,
  action text,
  actor_name text,
  target_user_id uuid,
  target_user_uid bigint,
  target_user_name text,
  report_id bigint,
  details jsonb,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select a.id, a.action, actor.username, target.id, target.user_uid, target.username,
    a.report_id, a.details, a.created_at
  from public.moderation_actions a
  join public.profiles actor on actor.id = a.actor_id
  left join public.profiles target on target.id = a.target_user_id
  where trim(coalesce(search_text, '')) = ''
    or a.action ilike '%' || trim(search_text) || '%'
    or actor.username ilike '%' || trim(search_text) || '%'
    or target.username ilike '%' || trim(search_text) || '%'
    or target.user_uid::text = trim(search_text)
  order by a.created_at desc
  limit greatest(1, least(coalesce(row_limit, 100), 300));
end;
$$;

create or replace function public.admin_list_moderation_appeals(
  status_filter text default 'all',
  search_text text default '',
  row_limit integer default 100
)
returns table (
  appeal_id bigint,
  user_id uuid,
  user_uid bigint,
  username text,
  display_title text,
  reason text,
  status text,
  created_at timestamptz,
  review_note text,
  reviewed_at timestamptz,
  reviewer_name text,
  restriction_reason text,
  restricted_until timestamptz
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select a.id, p.id, p.user_uid, p.username, p.display_title, a.reason, a.status, a.created_at,
    a.review_note, a.reviewed_at, reviewer.username, m.reason, m.banned_until
  from public.moderation_appeals a
  join public.profiles p on p.id = a.user_id
  left join public.profiles reviewer on reviewer.id = a.reviewed_by
  left join public.user_moderation m on m.user_id = a.user_id
  where (status_filter = 'all' or a.status = status_filter)
    and (
      trim(coalesce(search_text, '')) = ''
      or p.username ilike '%' || trim(search_text) || '%'
      or p.user_uid::text = trim(search_text)
      or a.reason ilike '%' || trim(search_text) || '%'
    )
  order by (a.status = 'pending') desc, a.created_at desc
  limit greatest(1, least(coalesce(row_limit, 100), 300));
end;
$$;

create or replace function public.admin_set_user_restriction(
  target_user uuid,
  duration_code text,
  violation_category text,
  restriction_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  until_value timestamptz;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if target_user = auth.uid() then raise exception 'CANNOT_BAN_SELF'; end if;
  if not exists(select 1 from public.profiles p where p.id = target_user) then raise exception 'USER_NOT_FOUND'; end if;
  if exists(select 1 from public.profiles p where p.id = target_user and p.is_admin = true) then raise exception 'CANNOT_BAN_ADMIN'; end if;
  if violation_category not in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other') then raise exception 'INVALID_CATEGORY'; end if;
  if duration_code not in ('3d', '7d', '30d', 'permanent') then raise exception 'INVALID_DURATION'; end if;
  if char_length(trim(restriction_reason)) not between 2 and 300 then raise exception 'INVALID_REASON'; end if;

  until_value := case duration_code
    when '3d' then now() + interval '3 days'
    when '7d' then now() + interval '7 days'
    when '30d' then now() + interval '30 days'
    else null
  end;

  insert into public.user_moderation(user_id, banned_until, reason, updated_at, updated_by, active, category, scope)
  values (target_user, until_value, trim(restriction_reason), now(), auth.uid(), true, violation_category, 'community')
  on conflict (user_id) do update set
    banned_until = excluded.banned_until,
    reason = excluded.reason,
    updated_at = now(),
    updated_by = auth.uid(),
    active = true,
    category = excluded.category,
    scope = excluded.scope;

  insert into public.moderation_strikes(user_id, category, points, reason, created_by)
  values (target_user, violation_category, 2, trim(restriction_reason), auth.uid());
  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'restrict_user', target_user,
    jsonb_build_object('duration', duration_code, 'until', until_value, 'category', violation_category, 'reason', trim(restriction_reason)));
end;
$$;

-- 保留旧接口，但修正为支持 active 状态，供旧页面与回退逻辑使用。
create or replace function public.set_user_ban(target_user uuid, ban_until timestamptz, ban_reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if target_user = auth.uid() then raise exception 'CANNOT_BAN_SELF'; end if;
  if not exists(select 1 from public.profiles p where p.id = target_user) then raise exception 'USER_NOT_FOUND'; end if;
  if exists(select 1 from public.profiles p where p.id = target_user and p.is_admin = true) then raise exception 'CANNOT_BAN_ADMIN'; end if;
  if char_length(trim(ban_reason)) not between 2 and 300 then raise exception 'INVALID_REASON'; end if;
  insert into public.user_moderation(user_id, banned_until, reason, updated_at, updated_by, active, category, scope)
  values (target_user, ban_until, trim(ban_reason), now(), auth.uid(), true, 'other', 'community')
  on conflict (user_id) do update set
    banned_until = excluded.banned_until, reason = excluded.reason, updated_at = now(), updated_by = auth.uid(), active = true;
  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'ban_user', target_user, jsonb_build_object('until', ban_until, 'reason', trim(ban_reason)));
end;
$$;

create or replace function public.clear_user_ban(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  update public.user_moderation
  set active = false, banned_until = now(), updated_at = now(), updated_by = auth.uid()
  where user_id = target_user;
  insert into public.moderation_actions(actor_id, action, target_user_id)
  values (auth.uid(), 'unrestrict_user', target_user);
end;
$$;

create or replace function public.admin_resolve_report(
  target_report_id bigint,
  review_decision text,
  violation_category text,
  penalty_code text,
  moderator_note text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.content_reports%rowtype;
  author_id uuid;
  content_snapshot text;
  effective_penalty text := coalesce(penalty_code, 'none');
  restricted_until timestamptz;
  strike_number bigint := 0;
  strike_points smallint := 1;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if review_decision not in ('dismiss', 'warn', 'delete', 'delete_penalty') then raise exception 'INVALID_DECISION'; end if;
  if violation_category not in ('harassment', 'privacy', 'spam', 'illegal', 'misinformation', 'other') then raise exception 'INVALID_CATEGORY'; end if;
  if effective_penalty not in ('none', 'auto', '3d', '7d', '30d', 'permanent') then raise exception 'INVALID_PENALTY'; end if;
  if char_length(trim(moderator_note)) not between 2 and 500 then raise exception 'REVIEW_NOTE_REQUIRED'; end if;

  select * into item from public.content_reports where id = target_report_id for update;
  if not found then raise exception 'REPORT_NOT_FOUND'; end if;
  if item.status <> 'pending' then raise exception 'CASE_ALREADY_REVIEWED'; end if;

  if item.target_type = 'forum_post' then
    select fp.author_id, left(fp.title || E'\n' || fp.content, 500) into author_id, content_snapshot
    from public.forum_posts fp where fp.id = item.target_id;
  elsif item.target_type = 'forum_reply' then
    select fr.author_id, left(fr.content, 500) into author_id, content_snapshot
    from public.forum_replies fr where fr.id = item.target_id;
  else
    select c.author_id, left(c.content, 500) into author_id, content_snapshot
    from public.comments c where c.id = item.target_id;
  end if;

  if review_decision in ('delete', 'delete_penalty') then
    if item.target_type = 'forum_post' then delete from public.forum_posts where id = item.target_id;
    elsif item.target_type = 'forum_reply' then delete from public.forum_replies where id = item.target_id;
    else delete from public.comments where id = item.target_id;
    end if;
  end if;

  if review_decision <> 'dismiss' and author_id is not null
     and not exists(select 1 from public.profiles p where p.id = author_id and p.is_admin = true) then
    strike_points := case when review_decision = 'warn' then 1 when review_decision = 'delete' then 2 else 3 end;
    insert into public.moderation_strikes(user_id, report_id, category, points, reason, created_by)
    values (author_id, item.id, violation_category, strike_points, trim(moderator_note), auth.uid());
    select count(*) into strike_number from public.moderation_strikes s where s.user_id = author_id;
  end if;

  if review_decision <> 'delete_penalty' then effective_penalty := 'none'; end if;
  if effective_penalty = 'auto' then
    effective_penalty := case when strike_number <= 1 then '3d' when strike_number = 2 then '7d' else 'permanent' end;
  end if;
  restricted_until := case effective_penalty
    when '3d' then now() + interval '3 days'
    when '7d' then now() + interval '7 days'
    when '30d' then now() + interval '30 days'
    else null
  end;

  if effective_penalty <> 'none' and author_id is not null then
    if author_id = auth.uid() then raise exception 'CANNOT_BAN_SELF'; end if;
    if exists(select 1 from public.profiles p where p.id = author_id and p.is_admin = true) then raise exception 'CANNOT_BAN_ADMIN'; end if;
    insert into public.user_moderation(user_id, banned_until, reason, updated_at, updated_by, active, category, scope)
    values (author_id, restricted_until, trim(moderator_note), now(), auth.uid(), true, violation_category, 'community')
    on conflict (user_id) do update set
      banned_until = excluded.banned_until, reason = excluded.reason, updated_at = now(), updated_by = auth.uid(),
      active = true, category = excluded.category, scope = excluded.scope;
  end if;

  if review_decision in ('delete', 'delete_penalty') then
    update public.content_reports r set
      status = 'resolved', reviewed_at = now(), reviewed_by = auth.uid(), category = violation_category,
      decision = review_decision, review_note = trim(moderator_note)
    where r.target_type = item.target_type and r.target_id = item.target_id and r.status = 'pending';
  else
    update public.content_reports r set
      status = case when review_decision = 'dismiss' then 'dismissed' else 'resolved' end,
      reviewed_at = now(), reviewed_by = auth.uid(), category = violation_category,
      decision = review_decision, review_note = trim(moderator_note)
    where r.id = item.id;
  end if;

  insert into public.moderation_actions(actor_id, action, target_user_id, report_id, details)
  values (auth.uid(), 'resolve_report', author_id, item.id, jsonb_build_object(
    'decision', review_decision, 'category', violation_category, 'penalty', effective_penalty,
    'restricted_until', restricted_until, 'note', trim(moderator_note),
    'target_type', item.target_type, 'target_id', item.target_id,
    'content_snapshot', coalesce(content_snapshot, '[内容已删除]'), 'strike_number', strike_number
  ));

  return jsonb_build_object('decision', review_decision, 'penalty', effective_penalty,
    'restricted_until', restricted_until, 'target_user_id', author_id);
end;
$$;

create or replace function public.admin_manage_member(
  target_user uuid,
  new_title text,
  role_action text default 'keep'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  target_is_admin boolean;
  admin_count bigint;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if role_action not in ('keep', 'promote', 'demote') then raise exception 'INVALID_ROLE_ACTION'; end if;
  if char_length(trim(new_title)) not between 1 and 30 then raise exception 'INVALID_TITLE'; end if;
  select p.is_admin into target_is_admin from public.profiles p where p.id = target_user for update;
  if not found then raise exception 'USER_NOT_FOUND'; end if;

  if role_action <> 'keep' and target_user = auth.uid() then raise exception 'CANNOT_CHANGE_SELF_ROLE'; end if;
  if role_action = 'demote' and target_is_admin then
    select count(*) into admin_count from public.profiles p where p.is_admin = true;
    if admin_count <= 1 then raise exception 'CANNOT_DEMOTE_LAST_ADMIN'; end if;
  end if;

  update public.profiles p set
    display_title = trim(new_title),
    title_locked = true,
    is_admin = case role_action when 'promote' then true when 'demote' then false else p.is_admin end
  where p.id = target_user;

  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'manage_member', target_user,
    jsonb_build_object('title', trim(new_title), 'role_action', role_action, 'previous_admin', target_is_admin));
  return true;
end;
$$;

-- 修复旧版站长面板：promote=false 只保持角色，不再隐式降级。
create or replace function public.admin_update_member(target_user uuid, new_title text, promote boolean default false)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.admin_manage_member(target_user, coalesce(nullif(trim(new_title), ''), '社区成员'),
    case when coalesce(promote, false) then 'promote' else 'keep' end);
end;
$$;

create or replace function public.submit_moderation_appeal(appeal_reason text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
  latest_action bigint;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if char_length(trim(appeal_reason)) not between 10 and 500 then raise exception 'INVALID_APPEAL_REASON'; end if;
  if not exists(select 1 from public.user_moderation m where m.user_id = auth.uid() and m.active = true and (m.banned_until is null or m.banned_until > now())) then
    raise exception 'NO_ACTIVE_RESTRICTION';
  end if;
  select a.id into latest_action from public.moderation_actions a
  where a.target_user_id = auth.uid()
    and (a.action in ('restrict_user', 'ban_user')
      or a.action = 'resolve_report' and coalesce(a.details->>'penalty', 'none') <> 'none')
  order by a.created_at desc limit 1;
  insert into public.moderation_appeals(user_id, action_id, reason)
  values (auth.uid(), latest_action, trim(appeal_reason)) returning id into new_id;
  return new_id;
exception
  when unique_violation then raise exception 'APPEAL_ALREADY_PENDING';
end;
$$;

create or replace function public.admin_review_moderation_appeal(
  target_appeal_id bigint,
  review_decision text,
  moderator_note text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  appeal public.moderation_appeals%rowtype;
  newer_action_exists boolean;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if review_decision not in ('approved', 'rejected') then raise exception 'INVALID_DECISION'; end if;
  if char_length(trim(moderator_note)) not between 2 and 500 then raise exception 'REVIEW_NOTE_REQUIRED'; end if;
  select * into appeal from public.moderation_appeals where id = target_appeal_id for update;
  if not found then raise exception 'APPEAL_NOT_FOUND'; end if;
  if appeal.status <> 'pending' then raise exception 'APPEAL_ALREADY_REVIEWED'; end if;

  select exists(
    select 1 from public.moderation_actions a
    where a.target_user_id = appeal.user_id
      and a.id > coalesce(appeal.action_id, 0)
      and (a.action in ('restrict_user', 'ban_user')
        or a.action = 'resolve_report' and coalesce(a.details->>'penalty', 'none') <> 'none')
  ) into newer_action_exists;
  if review_decision = 'approved' and newer_action_exists then raise exception 'APPEAL_SUPERSEDED'; end if;

  update public.moderation_appeals set status = review_decision, review_note = trim(moderator_note),
    reviewed_at = now(), reviewed_by = auth.uid()
  where id = target_appeal_id;
  if review_decision = 'approved' then
    update public.user_moderation set active = false, banned_until = now(), updated_at = now(), updated_by = auth.uid()
    where user_id = appeal.user_id;
  end if;
  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'review_appeal', appeal.user_id,
    jsonb_build_object('appeal_id', target_appeal_id, 'decision', review_decision, 'note', trim(moderator_note)));
end;
$$;

create or replace function public.admin_governance_maintenance()
returns table (expired_restrictions_closed integer, active_restrictions integer, pending_reports integer, pending_appeals integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  closed_count integer;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  update public.user_moderation m set active = false, updated_at = now(), updated_by = auth.uid()
  where m.active = true and m.banned_until is not null and m.banned_until <= now();
  get diagnostics closed_count = row_count;
  insert into public.moderation_actions(actor_id, action, details)
  values (auth.uid(), 'governance_maintenance', jsonb_build_object('expired_restrictions_closed', closed_count));
  return query select closed_count,
    (select count(*)::integer from public.user_moderation m where m.active = true and (m.banned_until is null or m.banned_until > now())),
    (select count(*)::integer from public.content_reports r where r.status = 'pending'),
    (select count(*)::integer from public.moderation_appeals a where a.status = 'pending');
end;
$$;

revoke all on function public.current_user_can_participate() from public;
revoke all on function public.protect_profile_governance_fields() from public;
revoke all on function public.get_my_moderation() from public;
revoke all on function public.get_my_governance_status() from public;
revoke all on function public.report_content_v2(text, bigint, text, text) from public;
revoke all on function public.admin_governance_overview() from public;
revoke all on function public.admin_get_member_by_uid(bigint) from public;
revoke all on function public.admin_list_moderation_users(text, text, integer) from public;
revoke all on function public.admin_list_moderation_reports(text, text, integer) from public;
revoke all on function public.admin_list_moderation_actions(text, integer) from public;
revoke all on function public.admin_list_moderation_appeals(text, text, integer) from public;
revoke all on function public.admin_set_user_restriction(uuid, text, text, text) from public;
revoke all on function public.set_user_ban(uuid, timestamptz, text) from public;
revoke all on function public.clear_user_ban(uuid) from public;
revoke all on function public.admin_resolve_report(bigint, text, text, text, text) from public;
revoke all on function public.admin_manage_member(uuid, text, text) from public;
revoke all on function public.admin_update_member(uuid, text, boolean) from public;
revoke all on function public.submit_moderation_appeal(text) from public;
revoke all on function public.admin_review_moderation_appeal(bigint, text, text) from public;
revoke all on function public.admin_governance_maintenance() from public;

grant execute on function public.current_user_can_participate() to authenticated;
grant execute on function public.get_my_moderation() to authenticated;
grant execute on function public.get_my_governance_status() to authenticated;
grant execute on function public.report_content_v2(text, bigint, text, text) to authenticated;
grant execute on function public.admin_governance_overview() to authenticated;
grant execute on function public.admin_get_member_by_uid(bigint) to authenticated;
grant execute on function public.admin_list_moderation_users(text, text, integer) to authenticated;
grant execute on function public.admin_list_moderation_reports(text, text, integer) to authenticated;
grant execute on function public.admin_list_moderation_actions(text, integer) to authenticated;
grant execute on function public.admin_list_moderation_appeals(text, text, integer) to authenticated;
grant execute on function public.admin_set_user_restriction(uuid, text, text, text) to authenticated;
grant execute on function public.set_user_ban(uuid, timestamptz, text) to authenticated;
grant execute on function public.clear_user_ban(uuid) to authenticated;
grant execute on function public.admin_resolve_report(bigint, text, text, text, text) to authenticated;
grant execute on function public.admin_manage_member(uuid, text, text) to authenticated;
grant execute on function public.admin_update_member(uuid, text, boolean) to authenticated;
grant execute on function public.submit_moderation_appeal(text) to authenticated;
grant execute on function public.admin_review_moderation_appeal(bigint, text, text) to authenticated;
grant execute on function public.admin_governance_maintenance() to authenticated;

notify pgrst, 'reload schema';
