-- Telegram 风格群聊初始化（可重复执行）。
-- 前置要求：community.sql、private-chat.sql、social-inbox.sql、chat-realtime.sql。
-- 在 Supabase Dashboard → SQL Editor 中完整执行本文件一次。

create table if not exists public.group_chats (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 40),
  description text not null default '' check (char_length(description) <= 200),
  avatar_url text check (avatar_url is null or char_length(avatar_url) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.group_chat_members (
  group_id uuid not null references public.group_chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member')),
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.group_chat_messages (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.group_chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 2000),
  created_at timestamptz not null default now()
);

-- 兼容引用/撤回升级列；基础脚本可重复执行
alter table public.group_chat_messages
  add column if not exists media_path text,
  add column if not exists reply_to_id bigint,
  add column if not exists revoked_at timestamptz;

create index if not exists group_chat_members_user_idx
  on public.group_chat_members(user_id, joined_at desc);
create index if not exists group_chat_messages_group_created_idx
  on public.group_chat_messages(group_id, created_at desc);

alter table public.group_chats enable row level security;
alter table public.group_chat_members enable row level security;
alter table public.group_chat_messages enable row level security;
revoke all on public.group_chats, public.group_chat_members, public.group_chat_messages from anon, authenticated;

create or replace function public.is_group_chat_member(requested_group uuid, requested_user uuid default auth.uid())
returns boolean
language sql stable security definer set search_path = public
as $$
  select requested_user is not null and exists (
    select 1 from public.group_chat_members
    where group_id = requested_group and user_id = requested_user
  );
$$;

create or replace function public.can_manage_group_chat(requested_group uuid, requested_user uuid default auth.uid())
returns boolean
language sql stable security definer set search_path = public
as $$
  select requested_user is not null and exists (
    select 1 from public.group_chat_members
    where group_id = requested_group
      and user_id = requested_user
      and role in ('owner', 'admin')
  );
$$;

drop policy if exists "Group members can receive group messages" on public.group_chat_messages;
create policy "Group members can receive group messages"
  on public.group_chat_messages for select to authenticated
  using (public.is_group_chat_member(group_id, (select auth.uid())));
grant select on public.group_chat_messages to authenticated;

create or replace function public.create_group_chat(
  p_name text,
  p_description text default '',
  p_avatar_url text default null,
  p_member_ids uuid[] default '{}'::uuid[]
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  new_group_id uuid;
  clean_name text := trim(coalesce(p_name, ''));
  clean_description text := trim(coalesce(p_description, ''));
  clean_avatar text := nullif(trim(coalesce(p_avatar_url, '')), '');
  clean_members uuid[];
  valid_members integer;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if char_length(clean_name) not between 2 and 40 then raise exception 'INVALID_GROUP_NAME'; end if;
  if char_length(clean_description) > 200 then raise exception 'INVALID_GROUP_DESCRIPTION'; end if;
  if clean_avatar is not null and char_length(clean_avatar) > 500 then raise exception 'INVALID_GROUP_AVATAR'; end if;

  select coalesce(array_agg(distinct member_id), '{}'::uuid[])
    into clean_members
  from unnest(coalesce(p_member_ids, '{}'::uuid[])) as member_id
  where member_id is not null and member_id <> auth.uid();

  if cardinality(clean_members) < 1 then raise exception 'GROUP_MEMBER_REQUIRED'; end if;
  if cardinality(clean_members) > 49 then raise exception 'GROUP_MEMBER_LIMIT'; end if;

  select count(*) into valid_members
  from unnest(clean_members) as member_id
  where exists (
      select 1 from public.user_follows
      where follower_id = auth.uid() and following_id = member_id
    ) and exists (
      select 1 from public.user_follows
      where follower_id = member_id and following_id = auth.uid()
    );
  if valid_members <> cardinality(clean_members) then raise exception 'MUTUAL_FOLLOW_REQUIRED'; end if;

  insert into public.group_chats(owner_id, name, description, avatar_url)
  values (auth.uid(), clean_name, clean_description, clean_avatar)
  returning id into new_group_id;

  insert into public.group_chat_members(group_id, user_id, role)
  values (new_group_id, auth.uid(), 'owner');
  insert into public.group_chat_members(group_id, user_id, role)
  select new_group_id, member_id, 'member' from unnest(clean_members) as member_id;
  insert into public.notifications(recipient_id, actor_id, kind, target_type, payload)
  select member_id, auth.uid(), 'group_message', 'group_chat', jsonb_build_object(
    'event', 'group_invite',
    'message', '邀请你加入群聊',
    'preview', '邀请你加入群聊',
    'group_id', new_group_id,
    'group_name', clean_name,
    'sender_name', coalesce((select username from public.profiles where id = auth.uid()), '社区用户'),
    'sender_avatar_url', (select avatar_url from public.profiles where id = auth.uid())
  ) from unnest(clean_members) as member_id;
  return new_group_id;
end;
$$;

create or replace function public.list_my_group_chats()
returns table (
  group_id uuid,
  group_name text,
  group_description text,
  group_avatar_url text,
  owner_id uuid,
  group_role text,
  member_count bigint,
  unread_count bigint,
  last_message text,
  last_message_at timestamptz,
  last_sender_name text
)
language sql stable security definer set search_path = public
as $$
  select g.id, g.name, g.description, g.avatar_url, g.owner_id, mine.role,
    (select count(*) from public.group_chat_members members where members.group_id = g.id),
    (select count(*) from public.group_chat_messages unread
      where unread.group_id = g.id
        and unread.sender_id <> auth.uid()
        and unread.created_at > mine.last_read_at),
    latest.content, latest.created_at, latest.sender_name
  from public.group_chat_members mine
  join public.group_chats g on g.id = mine.group_id
  left join lateral (
    select message.content, message.created_at, coalesce(sender.username, '社区用户') as sender_name
    from public.group_chat_messages message
    left join public.profiles sender on sender.id = message.sender_id
    where message.group_id = g.id
    order by message.created_at desc
    limit 1
  ) latest on true
  where mine.user_id = auth.uid()
  order by coalesce(latest.created_at, g.created_at) desc;
$$;

drop function if exists public.list_group_chat_messages(uuid, integer);
create function public.list_group_chat_messages(p_group_id uuid, p_limit integer default 120)
returns table (
  id bigint,
  group_id uuid,
  sender_id uuid,
  content text,
  media_path text,
  created_at timestamptz,
  sender_username text,
  sender_avatar_url text,
  sender_uid bigint,
  sender_title text,
  revoked_at timestamptz,
  reply_to_id bigint,
  reply_sender_id uuid,
  reply_sender_name text,
  reply_content text,
  reply_media_path text,
  reply_created_at timestamptz,
  reply_revoked_at timestamptz
)
language plpgsql stable security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.is_group_chat_member(p_group_id, auth.uid()) then raise exception 'GROUP_MEMBERSHIP_REQUIRED'; end if;
  return query
  select ordered.id, ordered.group_id, ordered.sender_id, ordered.content, ordered.media_path, ordered.created_at,
    ordered.sender_username, ordered.sender_avatar_url, ordered.sender_uid, ordered.sender_title, ordered.revoked_at,
    quoted.id as reply_to_id, quoted.sender_id as reply_sender_id,
    coalesce(quoted_sender.username, '社区用户') as reply_sender_name,
    quoted.content as reply_content, quoted.media_path as reply_media_path, quoted.created_at as reply_created_at,
    quoted.revoked_at as reply_revoked_at
  from (
    select message.id, message.group_id, message.sender_id, message.content, message.media_path, message.created_at, message.reply_to_id, message.revoked_at,
      coalesce(sender.username, '社区用户') as sender_username, sender.avatar_url as sender_avatar_url,
      sender.user_uid as sender_uid, sender.display_title as sender_title
    from public.group_chat_messages message
    left join public.profiles sender on sender.id = message.sender_id
    where message.group_id = p_group_id
    order by message.created_at desc
    limit least(greatest(coalesce(p_limit, 120), 1), 200)
  ) ordered
  left join public.group_chat_messages quoted on quoted.id = ordered.reply_to_id
  left join public.profiles quoted_sender on quoted_sender.id = quoted.sender_id
  order by ordered.created_at asc;
end;
$$;

create or replace function public.send_group_chat_message(p_group_id uuid, p_content text)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare
  new_message_id bigint;
  clean_content text := trim(coalesce(p_content, ''));
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.is_group_chat_member(p_group_id, auth.uid()) then raise exception 'GROUP_MEMBERSHIP_REQUIRED'; end if;
  if char_length(clean_content) not between 1 and 2000 then raise exception 'INVALID_MESSAGE'; end if;
  insert into public.group_chat_messages(group_id, sender_id, content)
  values (p_group_id, auth.uid(), clean_content)
  returning id into new_message_id;
  update public.group_chat_members set last_read_at = now()
  where group_id = p_group_id and user_id = auth.uid();
  return new_message_id;
end;
$$;

create or replace function public.mark_group_chat_read(p_group_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.is_group_chat_member(p_group_id, auth.uid()) then raise exception 'GROUP_MEMBERSHIP_REQUIRED'; end if;
  update public.group_chat_members set last_read_at = now()
  where group_id = p_group_id and user_id = auth.uid();
  update public.notifications set read_at = now()
  where recipient_id = auth.uid()
    and kind = 'group_message'
    and read_at is null
    and payload->>'group_id' = p_group_id::text;
end;
$$;

create or replace function public.list_group_chat_members(p_group_id uuid)
returns table (
  user_id uuid,
  user_uid bigint,
  username text,
  avatar_url text,
  display_title text,
  member_role text,
  joined_at timestamptz
)
language plpgsql stable security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.is_group_chat_member(p_group_id, auth.uid()) then raise exception 'GROUP_MEMBERSHIP_REQUIRED'; end if;
  return query
    select member.user_id, profile.user_uid, profile.username, profile.avatar_url,
      profile.display_title, member.role, member.joined_at
    from public.group_chat_members member
    join public.profiles profile on profile.id = member.user_id
    where member.group_id = p_group_id
    order by case member.role when 'owner' then 0 when 'admin' then 1 else 2 end,
      member.joined_at asc;
end;
$$;

create or replace function public.update_group_chat(
  p_group_id uuid,
  p_name text,
  p_description text default '',
  p_avatar_url text default null
)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  clean_name text := trim(coalesce(p_name, ''));
  clean_description text := trim(coalesce(p_description, ''));
  clean_avatar text := nullif(trim(coalesce(p_avatar_url, '')), '');
begin
  if not public.can_manage_group_chat(p_group_id, auth.uid()) then raise exception 'GROUP_ADMIN_REQUIRED'; end if;
  if char_length(clean_name) not between 2 and 40 then raise exception 'INVALID_GROUP_NAME'; end if;
  if char_length(clean_description) > 200 then raise exception 'INVALID_GROUP_DESCRIPTION'; end if;
  if clean_avatar is not null and char_length(clean_avatar) > 500 then raise exception 'INVALID_GROUP_AVATAR'; end if;
  update public.group_chats set name = clean_name, description = clean_description,
    avatar_url = clean_avatar, updated_at = now()
  where id = p_group_id;
  return found;
end;
$$;

create or replace function public.add_group_chat_members(p_group_id uuid, p_member_ids uuid[])
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  clean_members uuid[];
  valid_members integer;
  current_count integer;
  inserted_count integer;
begin
  if not public.can_manage_group_chat(p_group_id, auth.uid()) then raise exception 'GROUP_ADMIN_REQUIRED'; end if;
  select coalesce(array_agg(distinct member_id), '{}'::uuid[]) into clean_members
  from unnest(coalesce(p_member_ids, '{}'::uuid[])) as member_id
  where member_id is not null
    and member_id <> auth.uid()
    and not exists (
      select 1 from public.group_chat_members existing
      where existing.group_id = p_group_id and existing.user_id = member_id
    );
  if cardinality(clean_members) < 1 then return 0; end if;
  select count(*) into current_count from public.group_chat_members where group_id = p_group_id;
  if current_count + cardinality(clean_members) > 50 then raise exception 'GROUP_MEMBER_LIMIT'; end if;
  select count(*) into valid_members from unnest(clean_members) as member_id
  where exists (select 1 from public.user_follows where follower_id = auth.uid() and following_id = member_id)
    and exists (select 1 from public.user_follows where follower_id = member_id and following_id = auth.uid());
  if valid_members <> cardinality(clean_members) then raise exception 'MUTUAL_FOLLOW_REQUIRED'; end if;
  insert into public.group_chat_members(group_id, user_id, role)
  select p_group_id, member_id, 'member' from unnest(clean_members) as member_id
  on conflict (group_id, user_id) do nothing;
  get diagnostics inserted_count = row_count;
  insert into public.notifications(recipient_id, actor_id, kind, target_type, payload)
  select member_id, auth.uid(), 'group_message', 'group_chat', jsonb_build_object(
    'event', 'group_invite',
    'message', '邀请你加入群聊',
    'preview', '邀请你加入群聊',
    'group_id', p_group_id,
    'group_name', coalesce((select name from public.group_chats where id = p_group_id), '群聊'),
    'sender_name', coalesce((select username from public.profiles where id = auth.uid()), '社区用户'),
    'sender_avatar_url', (select avatar_url from public.profiles where id = auth.uid())
  ) from unnest(clean_members) as member_id;
  return inserted_count;
end;
$$;

create or replace function public.remove_group_chat_member(p_group_id uuid, p_user_id uuid)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  caller_role text;
  target_role text;
begin
  select role into caller_role from public.group_chat_members
  where group_id = p_group_id and user_id = auth.uid();
  select role into target_role from public.group_chat_members
  where group_id = p_group_id and user_id = p_user_id;
  if caller_role is null or caller_role not in ('owner', 'admin') then raise exception 'GROUP_ADMIN_REQUIRED'; end if;
  if target_role is null then return false; end if;
  if target_role = 'owner' or (target_role = 'admin' and caller_role <> 'owner') then raise exception 'CANNOT_REMOVE_GROUP_ADMIN'; end if;
  if p_user_id = auth.uid() then raise exception 'USE_LEAVE_GROUP'; end if;
  delete from public.notifications
  where recipient_id = p_user_id
    and kind = 'group_message'
    and payload->>'group_id' = p_group_id::text;
  delete from public.group_chat_members where group_id = p_group_id and user_id = p_user_id;
  return found;
end;
$$;

create or replace function public.leave_group_chat(p_group_id uuid)
returns boolean
language plpgsql security definer set search_path = public
as $$
declare
  leaving_role text;
  successor uuid;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select role into leaving_role from public.group_chat_members
  where group_id = p_group_id and user_id = auth.uid();
  if leaving_role is null then return false; end if;
  if leaving_role = 'owner' then
    select user_id into successor from public.group_chat_members
    where group_id = p_group_id and user_id <> auth.uid()
    order by case role when 'admin' then 0 else 1 end, joined_at asc limit 1;
    if successor is null then
      delete from public.notifications
      where kind = 'group_message' and payload->>'group_id' = p_group_id::text;
      delete from public.group_chats where id = p_group_id;
      return true;
    end if;
    update public.group_chat_members set role = 'owner'
    where group_id = p_group_id and user_id = successor;
    update public.group_chats set owner_id = successor, updated_at = now()
    where id = p_group_id;
  end if;
  delete from public.notifications
  where recipient_id = auth.uid()
    and kind = 'group_message'
    and payload->>'group_id' = p_group_id::text;
  delete from public.group_chat_members where group_id = p_group_id and user_id = auth.uid();
  return found;
end;
$$;

alter table public.notifications drop constraint if exists notifications_kind_check;
alter table public.notifications add constraint notifications_kind_check
  check (kind in ('follow', 'forum_like', 'comment_like', 'direct_message', 'forum_reply', 'group_message'));

create or replace function public.notify_group_chat_message_created()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  sender_name text;
  sender_avatar text;
  current_group_name text;
begin
  select username, avatar_url into sender_name, sender_avatar
  from public.profiles where id = new.sender_id;
  select name into current_group_name from public.group_chats where id = new.group_id;
  insert into public.notifications(recipient_id, actor_id, kind, target_type, payload)
  select member.user_id, new.sender_id, 'group_message', 'group_chat',
    jsonb_build_object(
      'message', '在群聊中发送了新消息',
      'preview', left(regexp_replace(new.content, '[[:space:]]+', ' ', 'g'), 80),
      'group_id', new.group_id,
      'group_name', coalesce(current_group_name, '群聊'),
      'sender_name', coalesce(sender_name, '社区用户'),
      'sender_avatar_url', sender_avatar
    )
  from public.group_chat_members member
  where member.group_id = new.group_id and member.user_id <> new.sender_id;
  return new;
end;
$$;

drop trigger if exists after_group_chat_message_created on public.group_chat_messages;
create trigger after_group_chat_message_created
  after insert on public.group_chat_messages
  for each row execute procedure public.notify_group_chat_message_created();

create or replace function public.mark_notifications_read()
returns void language sql security definer set search_path = public as $$
  update public.notifications set read_at = now()
  where recipient_id = auth.uid()
    and read_at is null
    and kind not in ('direct_message', 'group_message');
$$;

revoke all on function public.is_group_chat_member(uuid, uuid) from public;
revoke all on function public.can_manage_group_chat(uuid, uuid) from public;
revoke all on function public.create_group_chat(text, text, text, uuid[]) from public;
revoke all on function public.list_my_group_chats() from public;
revoke all on function public.list_group_chat_messages(uuid, integer) from public;
revoke all on function public.send_group_chat_message(uuid, text) from public;
revoke all on function public.mark_group_chat_read(uuid) from public;
revoke all on function public.list_group_chat_members(uuid) from public;
revoke all on function public.update_group_chat(uuid, text, text, text) from public;
revoke all on function public.add_group_chat_members(uuid, uuid[]) from public;
revoke all on function public.remove_group_chat_member(uuid, uuid) from public;
revoke all on function public.leave_group_chat(uuid) from public;
grant execute on function public.is_group_chat_member(uuid, uuid) to authenticated;
grant execute on function public.can_manage_group_chat(uuid, uuid) to authenticated;
grant execute on function public.create_group_chat(text, text, text, uuid[]) to authenticated;
grant execute on function public.list_my_group_chats() to authenticated;
grant execute on function public.list_group_chat_messages(uuid, integer) to authenticated;
grant execute on function public.send_group_chat_message(uuid, text) to authenticated;
grant execute on function public.mark_group_chat_read(uuid) to authenticated;
grant execute on function public.list_group_chat_members(uuid) to authenticated;
grant execute on function public.update_group_chat(uuid, text, text, text) to authenticated;
grant execute on function public.add_group_chat_members(uuid, uuid[]) to authenticated;
grant execute on function public.remove_group_chat_member(uuid, uuid) to authenticated;
grant execute on function public.leave_group_chat(uuid) to authenticated;
revoke all on function public.mark_notifications_read() from public;
grant execute on function public.mark_notifications_read() to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'group_chat_messages'
  ) then
    alter publication supabase_realtime add table public.group_chat_messages;
  end if;
end $$;

notify pgrst, 'reload schema';
