-- cnbdg 安全审核中心
-- 在 Supabase SQL Editor 中完整执行一次。
-- 不会删除已有用户或内容；所有管理操作都要求 profiles.is_admin = true。

create table if not exists public.user_moderation (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  banned_until timestamptz,
  reason text not null check (char_length(reason) between 2 and 300),
  updated_at timestamptz not null default now(),
  updated_by uuid not null references public.profiles(id) on delete restrict
);

create table if not exists public.content_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('forum_post', 'forum_reply', 'blog_comment')),
  target_id bigint not null,
  reason text not null check (char_length(reason) between 2 and 300),
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id) on delete set null
);

create unique index if not exists content_reports_one_pending_per_user_idx
  on public.content_reports(reporter_id, target_type, target_id)
  where status = 'pending';

create index if not exists content_reports_status_created_at_idx
  on public.content_reports(status, created_at desc);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  action text not null,
  target_user_id uuid references public.profiles(id) on delete set null,
  report_id bigint references public.content_reports(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_moderation enable row level security;
alter table public.content_reports enable row level security;
alter table public.moderation_actions enable row level security;

revoke all on table public.user_moderation from anon, authenticated;
revoke all on table public.content_reports from anon, authenticated;
revoke all on table public.moderation_actions from anon, authenticated;

grant select on table public.user_moderation to authenticated;
grant select on table public.content_reports to authenticated;
grant select on table public.moderation_actions to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Admins read moderation state" on public.user_moderation;
create policy "Admins read moderation state"
  on public.user_moderation for select
  using (public.current_user_is_admin());

drop policy if exists "Admins read reports" on public.content_reports;
create policy "Admins read reports"
  on public.content_reports for select
  using (public.current_user_is_admin());

drop policy if exists "Admins read moderation actions" on public.moderation_actions;
create policy "Admins read moderation actions"
  on public.moderation_actions for select
  using (public.current_user_is_admin());

create or replace function public.current_user_can_participate()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null and not exists (
    select 1 from public.user_moderation
    where user_id = auth.uid()
      and (banned_until is null or banned_until > now())
  );
$$;

revoke all on function public.current_user_can_participate() from public;
grant execute on function public.current_user_can_participate() to authenticated;

create or replace function public.get_my_moderation()
returns table (banned boolean, banned_until timestamptz, reason text)
language sql
stable
security definer
set search_path = public
as $$
  select
    (m.user_id is not null and (m.banned_until is null or m.banned_until > now())) as banned,
    m.banned_until,
    m.reason
  from (select auth.uid() as id) me
  left join public.user_moderation m
    on m.user_id = me.id and (m.banned_until is null or m.banned_until > now());
$$;

revoke all on function public.get_my_moderation() from public;
grant execute on function public.get_my_moderation() to authenticated;

-- 用封禁检查替换原有发布策略。
drop policy if exists "Signed-in users create own comments" on public.comments;
create policy "Signed-in users create own comments"
  on public.comments for insert
  with check (auth.uid() = author_id and public.current_user_can_participate());

drop policy if exists "Users create own forum posts" on public.forum_posts;
create policy "Users create own forum posts"
  on public.forum_posts for insert
  with check (auth.uid() = author_id and public.current_user_can_participate());

drop policy if exists "Users create own forum replies" on public.forum_replies;
create policy "Users create own forum replies"
  on public.forum_replies for insert
  with check (auth.uid() = author_id and public.current_user_can_participate());

create or replace function public.report_content(
  report_target_type text,
  report_target_id bigint,
  report_reason text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_id bigint;
  target_exists boolean;
begin
  if not public.current_user_can_participate() then
    raise exception 'ACCOUNT_RESTRICTED';
  end if;
  if report_target_type not in ('forum_post', 'forum_reply', 'blog_comment') then
    raise exception 'INVALID_TARGET';
  end if;
  if char_length(trim(report_reason)) not between 2 and 300 then
    raise exception 'INVALID_REASON';
  end if;

  if report_target_type = 'forum_post' then
    select exists(select 1 from public.forum_posts where id = report_target_id) into target_exists;
  elsif report_target_type = 'forum_reply' then
    select exists(select 1 from public.forum_replies where id = report_target_id) into target_exists;
  else
    select exists(select 1 from public.comments where id = report_target_id) into target_exists;
  end if;
  if not target_exists then raise exception 'TARGET_NOT_FOUND'; end if;

  insert into public.content_reports(reporter_id, target_type, target_id, reason)
  values (auth.uid(), report_target_type, report_target_id, trim(report_reason))
  returning id into new_id;
  return new_id;
exception
  when unique_violation then raise exception 'ALREADY_REPORTED';
end;
$$;

revoke all on function public.report_content(text, bigint, text) from public;
grant execute on function public.report_content(text, bigint, text) to authenticated;

create or replace function public.set_user_ban(
  target_user uuid,
  ban_until timestamptz,
  ban_reason text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if target_user = auth.uid() then raise exception 'CANNOT_BAN_SELF'; end if;
  if not exists(select 1 from public.profiles where id = target_user) then
    raise exception 'USER_NOT_FOUND';
  end if;
  if exists(select 1 from public.profiles where id = target_user and is_admin = true) then
    raise exception 'CANNOT_BAN_ADMIN';
  end if;
  if char_length(trim(ban_reason)) not between 2 and 300 then
    raise exception 'INVALID_REASON';
  end if;
  insert into public.user_moderation(user_id, banned_until, reason, updated_at, updated_by)
  values (target_user, ban_until, trim(ban_reason), now(), auth.uid())
  on conflict (user_id) do update set
    banned_until = excluded.banned_until,
    reason = excluded.reason,
    updated_at = now(),
    updated_by = auth.uid();
  insert into public.moderation_actions(actor_id, action, target_user_id, details)
  values (auth.uid(), 'ban_user', target_user, jsonb_build_object('until', ban_until, 'reason', trim(ban_reason)));
end;
$$;

create or replace function public.clear_user_ban(target_user uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  delete from public.user_moderation where user_id = target_user;
  insert into public.moderation_actions(actor_id, action, target_user_id)
  values (auth.uid(), 'unban_user', target_user);
end;
$$;

create or replace function public.list_moderation_users()
returns table (
  user_id uuid,
  username text,
  created_at timestamptz,
  banned boolean,
  banned_until timestamptz,
  ban_reason text,
  forum_post_count bigint,
  forum_reply_count bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select p.id, p.username, p.created_at,
    (m.user_id is not null and (m.banned_until is null or m.banned_until > now())),
    m.banned_until, m.reason,
    (select count(*) from public.forum_posts fp where fp.author_id = p.id),
    (select count(*) from public.forum_replies fr where fr.author_id = p.id)
  from public.profiles p
  left join public.user_moderation m on m.user_id = p.id
  order by p.created_at desc;
end;
$$;

create or replace function public.list_moderation_reports()
returns table (
  report_id bigint,
  target_type text,
  target_id bigint,
  reason text,
  status text,
  created_at timestamptz,
  reporter_name text,
  target_author_id uuid,
  target_author_name text,
  content_excerpt text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  return query
  select r.id, r.target_type, r.target_id, r.reason, r.status, r.created_at,
    reporter.username,
    case r.target_type
      when 'forum_post' then (select fp.author_id from public.forum_posts fp where fp.id = r.target_id)
      when 'forum_reply' then (select fr.author_id from public.forum_replies fr where fr.id = r.target_id)
      else (select c.author_id from public.comments c where c.id = r.target_id)
    end,
    case r.target_type
      when 'forum_post' then (select p.username from public.forum_posts fp join public.profiles p on p.id = fp.author_id where fp.id = r.target_id)
      when 'forum_reply' then (select p.username from public.forum_replies fr join public.profiles p on p.id = fr.author_id where fr.id = r.target_id)
      else (select p.username from public.comments c join public.profiles p on p.id = c.author_id where c.id = r.target_id)
    end,
    left(coalesce(case r.target_type
      when 'forum_post' then (select fp.title || E'\n' || fp.content from public.forum_posts fp where fp.id = r.target_id)
      when 'forum_reply' then (select fr.content from public.forum_replies fr where fr.id = r.target_id)
      else (select c.content from public.comments c where c.id = r.target_id)
    end, '[内容已删除]'), 500)
  from public.content_reports r
  join public.profiles reporter on reporter.id = r.reporter_id
  order by (r.status = 'pending') desc, r.created_at desc;
end;
$$;

create or replace function public.moderate_report(target_report_id bigint, decision text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.content_reports%rowtype;
  author_id uuid;
begin
  if not public.current_user_is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  if decision not in ('delete', 'dismiss') then raise exception 'INVALID_DECISION'; end if;
  select * into item from public.content_reports where id = target_report_id for update;
  if not found then raise exception 'REPORT_NOT_FOUND'; end if;

  if decision = 'delete' then
    if item.target_type = 'forum_post' then
      select fp.author_id into author_id from public.forum_posts fp where fp.id = item.target_id;
      delete from public.forum_posts where id = item.target_id;
    elsif item.target_type = 'forum_reply' then
      select fr.author_id into author_id from public.forum_replies fr where fr.id = item.target_id;
      delete from public.forum_replies where id = item.target_id;
    else
      select c.author_id into author_id from public.comments c where c.id = item.target_id;
      delete from public.comments where id = item.target_id;
    end if;
  end if;

  update public.content_reports set
    status = case when decision = 'delete' then 'resolved' else 'dismissed' end,
    reviewed_at = now(),
    reviewed_by = auth.uid()
  where id = target_report_id;
  insert into public.moderation_actions(actor_id, action, target_user_id, report_id, details)
  values (auth.uid(), decision || '_report', author_id, target_report_id,
    jsonb_build_object('target_type', item.target_type, 'target_id', item.target_id));
end;
$$;

revoke all on function public.set_user_ban(uuid, timestamptz, text) from public;
revoke all on function public.clear_user_ban(uuid) from public;
revoke all on function public.list_moderation_users() from public;
revoke all on function public.list_moderation_reports() from public;
revoke all on function public.moderate_report(bigint, text) from public;
grant execute on function public.set_user_ban(uuid, timestamptz, text) to authenticated;
grant execute on function public.clear_user_ban(uuid) to authenticated;
grant execute on function public.list_moderation_users() to authenticated;
grant execute on function public.list_moderation_reports() to authenticated;
grant execute on function public.moderate_report(bigint, text) to authenticated;
