-- 互相关注后私聊
-- 先执行 community.sql，再执行本脚本一次。
-- 消息内容只对双方可见，所有权限由 RLS 和安全函数强制执行。

create table if not exists public.user_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  check (follower_id <> following_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 2000),
  created_at timestamptz not null default now(),
  check (sender_id <> recipient_id)
);

-- 兼容媒体/引用/撤回升级列；基础脚本可重复执行
alter table public.direct_messages
  add column if not exists image_path text,
  add column if not exists reply_to_id bigint,
  add column if not exists revoked_at timestamptz;

create index if not exists direct_messages_pair_created_idx
  on public.direct_messages(sender_id, recipient_id, created_at);

alter table public.user_follows enable row level security;
alter table public.direct_messages enable row level security;
revoke all on table public.user_follows, public.direct_messages from anon, authenticated;

create or replace function public.get_follow_state(target_user uuid)
returns table (following boolean, followed_back boolean, mutual boolean)
language sql stable security definer set search_path = public
as $$
  select
    exists(select 1 from public.user_follows where follower_id = auth.uid() and following_id = target_user),
    exists(select 1 from public.user_follows where follower_id = target_user and following_id = auth.uid()),
    exists(select 1 from public.user_follows where follower_id = auth.uid() and following_id = target_user)
      and exists(select 1 from public.user_follows where follower_id = target_user and following_id = auth.uid());
$$;

create or replace function public.toggle_follow(target_user uuid)
returns table (following boolean, followed_back boolean, mutual boolean)
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if target_user = auth.uid() then raise exception 'CANNOT_FOLLOW_SELF'; end if;
  if not exists(select 1 from public.profiles where id = target_user) then raise exception 'USER_NOT_FOUND'; end if;
  if exists(select 1 from public.user_follows where follower_id = auth.uid() and following_id = target_user) then
    delete from public.user_follows where follower_id = auth.uid() and following_id = target_user;
  else
    insert into public.user_follows(follower_id, following_id) values (auth.uid(), target_user);
  end if;
  return query select * from public.get_follow_state(target_user);
end;
$$;

create or replace function public.send_direct_message(recipient_user uuid, message_content text)
returns bigint
language plpgsql security definer set search_path = public
as $$
declare new_id bigint;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if recipient_user = auth.uid() then raise exception 'CANNOT_MESSAGE_SELF'; end if;
  if char_length(trim(message_content)) not between 1 and 2000 then raise exception 'INVALID_MESSAGE'; end if;
  if not (
    exists(select 1 from public.user_follows where follower_id = auth.uid() and following_id = recipient_user)
    and exists(select 1 from public.user_follows where follower_id = recipient_user and following_id = auth.uid())
  ) then raise exception 'MUTUAL_FOLLOW_REQUIRED'; end if;
  insert into public.direct_messages(sender_id, recipient_id, content)
  values (auth.uid(), recipient_user, trim(message_content)) returning id into new_id;
  return new_id;
end;
$$;

drop function if exists public.list_direct_messages(uuid);
create function public.list_direct_messages(other_user uuid)
returns table (
  id bigint,
  sender_id uuid,
  recipient_id uuid,
  content text,
  image_path text,
  created_at timestamptz,
  revoked_at timestamptz,
  reply_to_id bigint,
  reply_sender_id uuid,
  reply_sender_name text,
  reply_content text,
  reply_image_path text,
  reply_created_at timestamptz,
  reply_revoked_at timestamptz
)
language plpgsql stable security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.can_send_direct_media_path(other_user::text) then raise exception 'MUTUAL_FOLLOW_REQUIRED'; end if;
  return query
  select m.id, m.sender_id, m.recipient_id, m.content, m.image_path, m.created_at, m.revoked_at,
    quoted.id as reply_to_id, quoted.sender_id as reply_sender_id,
    coalesce(quoted_sender.username, '社区用户') as reply_sender_name,
    quoted.content as reply_content, quoted.image_path as reply_image_path, quoted.created_at as reply_created_at,
    quoted.revoked_at as reply_revoked_at
  from public.direct_messages m
  left join public.direct_messages quoted on quoted.id = m.reply_to_id
  left join public.profiles quoted_sender on quoted_sender.id = quoted.sender_id
  where (m.sender_id = auth.uid() and m.recipient_id = other_user)
     or (m.sender_id = other_user and m.recipient_id = auth.uid())
  order by m.created_at asc;
end;
$$;

revoke all on function public.get_follow_state(uuid) from public;
revoke all on function public.toggle_follow(uuid) from public;
revoke all on function public.send_direct_message(uuid, text) from public;
revoke all on function public.list_direct_messages(uuid) from public;
grant execute on function public.get_follow_state(uuid) to authenticated;
grant execute on function public.toggle_follow(uuid) to authenticated;
grant execute on function public.send_direct_message(uuid, text) to authenticated;
grant execute on function public.list_direct_messages(uuid) to authenticated;
grant usage, select on all sequences in schema public to authenticated;
