-- 社区通知与好友栏。先执行 private-chat.sql、forum-interactions.sql，再执行本脚本。
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('follow','forum_like','comment_like')),
  target_type text,
  target_id bigint,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_recipient_created_idx on public.notifications(recipient_id, created_at desc);
alter table public.notifications enable row level security;
revoke all on public.notifications from anon, authenticated;

create or replace function public.notify_follow_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications(recipient_id, actor_id, kind, payload)
  values (new.following_id, new.follower_id, 'follow', jsonb_build_object('message','关注了你'));
  return new;
end; $$;
drop trigger if exists after_follow_created on public.user_follows;
create trigger after_follow_created after insert on public.user_follows for each row execute procedure public.notify_follow_created();

create or replace function public.notify_forum_like_created()
returns trigger language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if new.target_type = 'post' then select author_id into owner_id from public.forum_posts where id = new.target_id;
  else select author_id into owner_id from public.forum_replies where id = new.target_id;
  end if;
  if owner_id is not null and owner_id <> new.user_id then
    insert into public.notifications(recipient_id, actor_id, kind, target_type, target_id, payload)
    values (owner_id, new.user_id, 'forum_like', new.target_type, new.target_id, jsonb_build_object('message','赞了你的社区内容'));
  end if;
  return new;
end; $$;
drop trigger if exists after_forum_like_created on public.forum_reactions;
create trigger after_forum_like_created after insert on public.forum_reactions for each row execute procedure public.notify_forum_like_created();

-- 兼容博客评论点赞：保留原有计数逻辑，同时给评论作者生成通知。
create or replace function public.increment_comment_likes(comment_id bigint)
returns void language plpgsql security definer set search_path = public as $$
declare owner_id uuid;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  select author_id into owner_id from public.comments where id = comment_id;
  update public.comments set likes = likes + 1 where id = comment_id;
  if owner_id is not null and owner_id <> auth.uid() then
    insert into public.notifications(recipient_id, actor_id, kind, target_type, target_id, payload)
    values (owner_id, auth.uid(), 'comment_like', 'comment', comment_id, jsonb_build_object('message','赞了你的博客评论'));
  end if;
end; $$;

create or replace function public.list_notifications(p_limit integer default 50)
returns table(id bigint, kind text, target_type text, target_id bigint, payload jsonb, read_at timestamptz, created_at timestamptz, actor_id uuid, actor_username text, actor_avatar_url text, actor_uid bigint)
language sql security definer set search_path = public as $$
  select n.id,n.kind,n.target_type,n.target_id,n.payload,n.read_at,n.created_at,n.actor_id,p.username,p.avatar_url,p.user_uid
  from public.notifications n left join public.profiles p on p.id=n.actor_id
  where n.recipient_id=auth.uid() order by n.created_at desc limit least(greatest(coalesce(p_limit,50),1),100);
$$;
create or replace function public.mark_notifications_read()
returns void language sql security definer set search_path = public as $$ update public.notifications set read_at=now() where recipient_id=auth.uid() and read_at is null; $$;
create or replace function public.list_friends()
returns table(id uuid, user_uid bigint, username text, avatar_url text, display_title text, is_admin boolean, created_at timestamptz)
language sql security definer set search_path = public as $$
  select p.id,p.user_uid,p.username,p.avatar_url,p.display_title,p.is_admin,p.created_at
  from public.profiles p where p.id <> auth.uid()
    and exists(select 1 from public.user_follows a where a.follower_id=auth.uid() and a.following_id=p.id)
    and exists(select 1 from public.user_follows b where b.follower_id=p.id and b.following_id=auth.uid())
  order by p.username;
$$;
revoke all on function public.list_notifications(integer), public.mark_notifications_read(), public.list_friends() from public;
grant execute on function public.list_notifications(integer), public.mark_notifications_read(), public.list_friends() to authenticated;
revoke all on function public.increment_comment_likes(bigint) from public;
grant execute on function public.increment_comment_likes(bigint) to authenticated;
notify pgrst, 'reload schema';
