-- 在 Supabase 项目的 SQL Editor 中执行一次。
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null check (char_length(username) between 1 and 20),
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.comments (
  id bigint generated by default as identity primary key,
  post_id integer not null,
  author_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(content) between 1 and 500),
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

create index comments_post_id_created_at_idx on public.comments(post_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (new.id, coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.comments enable row level security;

create policy "Profiles are publicly readable" on public.profiles for select using (true);
create policy "Users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Comments are publicly readable" on public.comments for select using (true);
create policy "Signed-in users create own comments" on public.comments for insert
  with check (auth.uid() = author_id);
create policy "Users delete own comments" on public.comments for delete
  using (auth.uid() = author_id);

create or replace function public.increment_comment_likes(comment_id bigint)
returns void language sql security definer set search_path = public
as $$
  update public.comments set likes = likes + 1 where id = comment_id;
$$;

revoke all on function public.increment_comment_likes(bigint) from public;
grant execute on function public.increment_comment_likes(bigint) to authenticated;
